### ISSUE TITLE
Legal

### ISSUE THREAD

**Issue by HBiSoft** [JPatrickDev/BBC-Sport-API#1]
Is it legal using this commercially?

**Comment by JPatrickDev** [comment]
Hi, 

While I personally wouldn't have a problem with it, I wouldn't recommend it - It can't be trusted to be reliable and the BBC could block your IP at any time. It's currently going through a pretty major rewrite due to the BBC rewriting their site, and the BBC can easily break it again without any notice and I doubt that'd be acceptable in a commercial environment.
It's designed for purely personal use, where it's used as a fun/useful thing but also doesn't matter if it randomly stops working. 

Thanks, 
               Jack
